# Generated by Django 4.1 on 2022-08-15 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategoryId', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=500)),
                ('CategoryAncestorId', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('PlayerId', models.AutoField(primary_key=True, serialize=False)),
                ('PlayerName', models.CharField(max_length=500)),
                ('DateOfBirth', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoryApp.categories')),
            ],
        ),
    ]
